---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /src
  path: trieres

steps:
  - name: test
    image: golang:1.13
    commands:
      - mkdir ~/.ssh
      - echo "test" > ~/.ssh/id_rsa
      - mkdir -p /go/bin
      - go mod download
      - make test
  - name: build
    image: golang:1.13
    commands:
      - ./hack/build.sh
    environment:
      BUILD_ARCHS: "linux/amd64 linux/arm64 linux/arm darwin/amd64 windows/amd64"
